# Generated by Django 3.0.7 on 2020-06-15 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20200615_1737'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Staff',
            new_name='StaffMember',
        ),
    ]
