# Generated by Django 3.0.7 on 2020-06-17 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feedback',
            new_name='Contact',
        ),
    ]
